# Generated by Django 3.1.4 on 2021-02-09 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('account_type', models.CharField(choices=[(None, '(Unknown)'), ('PR', 'Personal'), ('GI', 'Influencer'), ('LI', 'Lifestyle Influencer'), ('FI', 'Fashion Influencer'), ('TI', 'Travel Influencer'), ('BR', 'Brand'), ('AD', 'Admin')], default='PR', max_length=2)),
                ('provider', models.CharField(choices=[(None, '(Unknown)'), ('email', 'Email'), ('facebook', 'Facebook')], default='email', max_length=10)),
                ('modified_username', models.BooleanField(blank=True, default=False)),
                ('profile_picture', models.ImageField(blank=True, max_length=1000, upload_to=users.models.pro_pic_dest)),
                ('user_bio', models.CharField(blank=True, default='', max_length=500)),
                ('user_website', models.URLField(blank=True, default='', max_length=2000)),
                ('is_premium', models.BooleanField(default=False)),
                ('sent_insta_email', models.BooleanField(blank=True, default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'sd_users',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_user', to=settings.AUTH_USER_MODEL)),
                ('wishlist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_item', to='components.componentpost')),
            ],
            options={
                'db_table': 'sd_wishlists',
            },
        ),
        migrations.AddField(
            model_name='useraccount',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist', through='users.Wishlist', to='components.ComponentPost'),
        ),
    ]
