# Generated by Django 3.1.4 on 2021-03-11 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210210_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_id', models.CharField(max_length=50)),
                ('access_token', models.CharField(max_length=250)),
                ('last_post', models.CharField(blank=True, default='', max_length=100)),
                ('expires_on', models.DateTimeField(default=users.models.get_expire_date)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insta_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sd_insta_tokens',
            },
        ),
    ]
