# Generated by Django 3.1.4 on 2021-02-09 08:36

from django.db import migrations, models
import django.db.models.deletion
import mainposts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.FileField(blank=True, max_length=1000, upload_to=mainposts.models.main_post_media_dest)),
                ('media_type', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('IM', 'Image'), ('VD', 'Video')], max_length=2)),
                ('caption', models.CharField(blank=True, max_length=2000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('OTD', 'OOTD'), ('SEO', 'Special Event Outfit'), ('HOM', 'Home'), ('BAG', 'Bag'), ('BSH', 'Bookshelf'), ('TLD', 'Travel Diaries'), ('RSP', 'Restaurant Picks'), ('MFG', 'My Favorite Gadgets'), ('MFA', 'My Favorite Apps'), ('MFM', 'My Favorite Movies')], default='OTD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sd_main_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MainpostComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('component_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_in_mainpost', to='components.componentpost')),
                ('mainpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainposts.mainpost')),
            ],
            options={
                'db_table': 'sd_mainpost_components',
            },
        ),
        migrations.AddField(
            model_name='mainpost',
            name='component_posts',
            field=models.ManyToManyField(related_name='mainpost_components', through='mainposts.MainpostComponent', to='components.ComponentPost'),
        ),
    ]
