# Generated by Django 3.1.4 on 2021-02-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainposts', '0002_mainpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpost',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
