# Generated by Django 3.1.4 on 2021-02-09 08:36

import components.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=150, unique=True)),
                ('xpath', models.CharField(max_length=1000)),
                ('shop_site', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sd_site_records',
            },
        ),
        migrations.CreateModel(
            name='ComponentPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.ImageField(blank=True, max_length=1000, upload_to=components.models.component_pic_dest)),
                ('page_url', models.URLField(max_length=1000)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('site_records', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_records', to='components.siterecord')),
            ],
            options={
                'db_table': 'sd_component_posts',
            },
        ),
    ]
